management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081

ashley:
  korean:
    hello: "안녕하세요"
  english:
    hello: "HELLO000"

spring:
  thymeleaf:

#--------------
#spring:
#  profiles:
#    active:
#      on-profile:
#        -produnction
#        -real
